config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "items#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :items do
    resources :orders, only: [:index, :new, :create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_item_like
  before_action :authenticate_user!   # ログイン中のユーザーのみに許可

  def create
    if @item.user_id != current_user.id
      @item_like = current_user.likes.build(item_id: params[:item_id])#Like.new(user_id: current_user.id, item_id: params[:item_id])
      @item_like.save
      respond_to do |format|
        format.js
      end
    end
  end  

  def destroy
    if @item.user_id != current_user.id
      @item_like = Like.find_by(user_id: current_user.id, item_id: params[:item_id])
      @item_like.delete
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def set_item_like
    @item = Item.find(params[:item_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? && item.liked_by?(current_user)%>
  <%=link_to "お気に入り解除", item_like_path(item.id),  data: { turbo_method: :delete }, class: "item_likes" , remote: true %><%= item.likes.count %>
<% else %>
  <%=link_to "お気に入り", item_likes_path(item.id), data: { turbo_method: :post }, class: "item_likes" , remote: true %><%= item.likes.count %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('favorite-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/destroy.js.erb
document.getElementById('favorite-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"